# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

imports:
    - { resource: version.yaml }
    - { resource: config.yaml }

parameters:
    commonmark.config:
        renderer:
            block_separator: "\n"
            inner_separator: "\n"
            soft_break: "\n"
        enable_em: true,
        enable_strong: true,
        use_asterisk: true,
        use_underscore: true,
        html_input: 'escape'
        allow_unsafe_links: false
        default_attributes:
            League\CommonMark\Extension\Table\Table:
                class: 'table table-striped table-hover align-td-middle'
            League\CommonMark\Extension\CommonMark\Node\Block\BlockQuote:
                class: 'blockquote'
        table:
            wrap:
                enabled: true
                tag: div
                attributes:
                    class: 'table-responsive'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Infrastructure/DependencyInjection'
            - '../src/**/Entity'
            - '../src/Request/Data'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #App\Doctrine\:
    #    resource: '../src/Doctrine/*Subscriber.php'
    #    tags: ['doctrine.event_subscriber']

    # SESSIONS
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            $pdoOrDsn: '%env(DATABASE_URL)%'

    # SAML
    LightSaml\SpBundle\Security\User\UsernameMapperInterface:
        alias: lightsaml_sp.username_mapper.simple

    LightSaml\Store\Id\IdStoreInterface:
        class: SchulIT\CommonBundle\Store\IdStore

    SchulIT\CommonBundle\Command\CreateCertificateCommand:
        arguments:
            $types:
                saml:
                    keyFile: '%sp_cert_key%'
                    certFile: '%sp_cert_file%'
                oauth2:
                    keyFile: '%kernel.project_dir%/oauth/oauth.key'
                    certFile: '%kernel.project_dir%/oauth/oauth.pub'

    SchulIT\CommonBundle\EventSubscriber\SamlExceptionSubscriber:
        arguments:
            $retryRoute: 'lightsaml_sp.login'
            $loggedInRoute: 'dashboard'

    # JSON
    #App\Request\JsonParamConverter:
    #    class:
    #    arguments:
    #        $prefixes:
    #            - 'App\Request\Data'
    #            - 'App\Request\Book'
    #            - 'App\Request\Message'

    JMS\Serializer\SerializationContext:
        calls:
            - [ setSerializeNull, [ true ]]

    JMS\Serializer\ContextFactory\DeserializationContextFactoryInterface:
        alias: 'jms_serializer.configured_deserialization_context_factory'

    App\Common\Security\ImportUserAuthenticator:
        arguments:
            $presharedKey: '%env(IMPORT_PSK)%'

    # SECURITY
    App\Common\Security\User\UserMapper:
        arguments:
            $typesMap: '%types_map%'

    # MENU
    App\Infrastructure\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: mainMenu }

    App\Infrastructure\Menu\ServicesMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: servicesMenu, alias: servicesMenu }

    App\Infrastructure\Menu\ImportMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: importMenu, alias: importMenu }

    App\Infrastructure\Menu\UserMenuBuilder:
        arguments:
            $idpProfileUrl: '%env(IDP_PROFILE_URL)%'
        tags:
            - { name: knp_menu.menu_builder, method: userMenu, alias: userMenu }

    App\Infrastructure\Menu\AdminMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: adminMenu, alias: adminMenu }

    App\Infrastructure\Menu\AdminDataMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: dataMenu, alias: dataMenu }

    App\Infrastructure\Menu\AdminToolsMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: toolsMenu, alias: toolsMenu }

    SchulIT\CommonBundle\Menu\Voter:
        tags:
            - { name: knp_menu.voter }

    # CONTROLLER
    App\Wiki\Controller\WikiAdminController:
        bind:
            $wikiFilesystem: '@oneup_flysystem.wiki_filesystem'

    App\Wiki\Controller\WikiController:
        bind:
            $wikiFilesystem: '@oneup_flysystem.wiki_filesystem'

    App\StudentAbsence\Controller\StudentAbsenceController:
        bind:
            $studentAbsencesFilesystem: '@oneup_flysystem.student_absence_filesystem'

    # MARKDOWN
    League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension: ~

    League\CommonMark\Extension\Autolink\AutolinkExtension: ~

    League\CommonMark\Extension\Table\TableExtension: ~

    League\CommonMark\Extension\DefaultAttributes\DefaultAttributesExtension: ~

    League\CommonMark\Environment\EnvironmentInterface:
        class: League\CommonMark\Environment\Environment
        arguments:
            $config: "%commonmark.config%"
        calls:
            - [ addExtension, [ "@League\\CommonMark\\Extension\\CommonMark\\CommonMarkCoreExtension" ]]
            - [ addExtension, [ "@League\\CommonMark\\Extension\\Autolink\\AutolinkExtension"]]
            - [ addExtension, [ "@League\\CommonMark\\Extension\\Table\\TableExtension"]]
            - [ addExtension, [ "@League\\CommonMark\\Extension\\DefaultAttributes\\DefaultAttributesExtension"]]
            - [ addExtension, [ "@App\\Infrastructure\\Markdown\\MarkdownExtension" ]]

    League\CommonMark\ConverterInterface:
        class: League\CommonMark\MarkdownConverter
        arguments:
            $environment: "@League\\CommonMark\\Environment\\EnvironmentInterface"

    EasySlugger\SluggerInterface:
        class: EasySlugger\Utf8Slugger

    Mimey\MimeTypes: ~

    # CONVERTER
    App\Framework\Converter\EnumStringConverter:
        bind:
            $enumFormKeyMapping:
                gender: App\Common\Entity\Gender
                grade_teacher_type: App\Common\Entity\GradeTeacherType
                message_scope: App\Message\Entity\MessageScope
                message_priority: App\Message\Entity\MessagePriority
                study_group_type: App\Common\Entity\StudyGroupType
                user_type: App\Common\Entity\UserType
                ics_access_token_type: App\Common\Entity\IcsAccessTokenType
                display_target_user_type: App\Display\Entity\DisplayTargetUserType
                absence_reason: App\Dashboard\AbsenceReason
                sick_reason: App\Book\Entity\SickNoteReason
                student_id_format: App\Untis\StudentIdFormat
                student_information_type: App\Common\Entity\StudentInformationType

    # DOCTRINE:
    Doctrine\Persistence\ManagerRegistry:
        alias: 'doctrine'

    Doctrine\Migrations\Version\DbalMigrationFactory: ~

    App\Infrastructure\Migrations\Factory\MigrationFactoryDecorator:
        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
        arguments:
            $migrationFactory: '@App\Infrastructure\Migrations\Factory\MigrationFactoryDecorator.inner'

    # DARK MODE:
    SchulIT\CommonBundle\DarkMode\DarkModeManagerInterface:
        class: App\Infrastructure\DarkMode\DarkModeManager

    # NOTIFICATIONS
    App\TeacherAbsence\TeacherAbsenceNotifier:
        arguments:
            $appName: '%env(APP_NAME)%'
            $sender: '%env(MAILER_FROM)%'

    # COMMANDS
    App\Infrastructure\Command\BackupCommand:
        arguments:
            $projectPath: '%kernel.project_dir%'
            $databaseDsn: '%env(DATABASE_URL)%'
            $backupDirectory: '%kernel.project_dir%/backup'
            $tempDirectory: '%kernel.project_dir%/backup/tmp'
            $files:
                - '.env.local'
            $directories:
                - 'files'
                - 'saml'

    App\Infrastructure\Command\RestoreCommand:
        arguments:
            $projectPath: '%kernel.project_dir%'
            $databaseDsn: '%env(DATABASE_URL)%'
            $backupDirectory: '%kernel.project_dir%/backup'
            $tempDirectory: '%kernel.project_dir%/backup/tmp'
            $files:
                - '.env.local'
            $directories:
                - 'files'
                - 'saml'

    Zenstruck\Messenger\Monitor\Command\PurgeCommand:
        tags:
            - { name: scheduler.task, arguments: '', trigger: 'cron', expression: '@daily' }

    SchulIT\CommonBundle\Command\ClearLogsCommand:
        tags:
            - { name: scheduler.task, arguments: '', trigger: 'cron', expression: '@daily' }

    # SECTION
    App\Common\Section\SectionResolver: ~

    App\Common\Section\CachedSectionResolver:
        decorates: App\Common\Section\SectionResolver
        bind:
            $sectionResolver: '@.inner'
            $cache: '@app.cache.memory'

    App\Common\Section\SectionResolverInterface:
        alias: App\Common\Section\CachedSectionResolver

    # MONOLOG
    SchulIT\CommonBundle\Monolog\DatabaseHandler:
        arguments:
            $connection: '@doctrine.dbal.logger_connection'
        calls:
            - setFormatter: [ '@SchulIT\CommonBundle\Monolog\LineFormatter']

    SchulIT\CommonBundle\Monolog\UsernameProcessor:
        tags:
            - { name: monolog.processor }
    SchulIT\CommonBundle\Monolog\LineFormatter: ~
    SchulIT\CommonBundle\Monolog\RequestProcessor:
        tags:
            - { name: monolog.processor }
    App\Infrastructure\Monolog\SqlAwareExceptionProcessor:
        tags:
            - { name: monolog.processor }

    # TWIG
    App\Infrastructure\Twig\WebpackEntryCssSourceExtension:
        bind:
            $publicDir: '%kernel.project_dir%/public'

