<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200629124952 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE user (id INT UNSIGNED AUTO_INCREMENT NOT NULL, teacher_id INT UNSIGNED DEFAULT NULL, idp_id CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', username VARCHAR(255) NOT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, user_type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:user_type)\', is_substitution_notifications_enabled TINYINT(1) NOT NULL, is_exam_notifications_enabled TINYINT(1) NOT NULL, is_message_notifications_enabled TINYINT(1) NOT NULL, is_email_notifications_enabled TINYINT(1) NOT NULL, data JSON NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D64941807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_students (user_id INT UNSIGNED NOT NULL, student_id INT UNSIGNED NOT NULL, INDEX IDX_44E469B2A76ED395 (user_id), INDEX IDX_44E469B2CB944F1A (student_id), PRIMARY KEY(user_id, student_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_dismissed_messages (user_id INT UNSIGNED NOT NULL, message_id INT UNSIGNED NOT NULL, INDEX IDX_E1D43738A76ED395 (user_id), INDEX IDX_E1D43738537A1329 (message_id), PRIMARY KEY(user_id, message_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE absence (id INT UNSIGNED AUTO_INCREMENT NOT NULL, teacher_id INT UNSIGNED DEFAULT NULL, study_group_id INT UNSIGNED DEFAULT NULL, room_id INT UNSIGNED DEFAULT NULL, date DATE NOT NULL, lesson_start INT DEFAULT NULL, lesson_end INT DEFAULT NULL, INDEX IDX_765AE0C941807E1D (teacher_id), INDEX IDX_765AE0C95DDDCCCE (study_group_id), INDEX IDX_765AE0C954177093 (room_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment (id INT UNSIGNED AUTO_INCREMENT NOT NULL, category_id INT UNSIGNED DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT DEFAULT NULL, start DATETIME NOT NULL, end DATETIME DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, all_day TINYINT(1) NOT NULL, mark_students_absent TINYINT(1) NOT NULL, external_organizers VARCHAR(255) DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_FE38F8449F75D7B0 (external_id), INDEX IDX_FE38F84412469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment_studygroups (appointment_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_5EE7E790E5B533F9 (appointment_id), INDEX IDX_5EE7E7905DDDCCCE (study_group_id), PRIMARY KEY(appointment_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment_organizers (appointment_id INT UNSIGNED NOT NULL, teacher_id INT UNSIGNED NOT NULL, INDEX IDX_ABD20936E5B533F9 (appointment_id), INDEX IDX_ABD2093641807E1D (teacher_id), PRIMARY KEY(appointment_id, teacher_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment_visibilities (appointment_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_9A6E5842E5B533F9 (appointment_id), INDEX IDX_9A6E58425E66E314 (user_type_entity_id), PRIMARY KEY(appointment_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment_category (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(255) DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_336892099F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT UNSIGNED AUTO_INCREMENT NOT NULL, category_id INT UNSIGNED DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, updated_at DATETIME NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_D8698A7612469DE2 (category_id), FULLTEXT INDEX IDX_D8698A762B36786B (title), FULLTEXT INDEX IDX_D8698A76FEC530A9 (content), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_studygroups (document_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_A786B266C33F7837 (document_id), INDEX IDX_A786B2665DDDCCCE (study_group_id), PRIMARY KEY(document_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_visibilities (document_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_CE496E3EC33F7837 (document_id), INDEX IDX_CE496E3E5E66E314 (user_type_entity_id), PRIMARY KEY(document_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_authors (document_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, INDEX IDX_2A638C8DC33F7837 (document_id), INDEX IDX_2A638C8DA76ED395 (user_id), PRIMARY KEY(document_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_attachment (id INT UNSIGNED AUTO_INCREMENT NOT NULL, document_id INT UNSIGNED DEFAULT NULL, filename LONGTEXT NOT NULL, path VARCHAR(255) NOT NULL, size INT NOT NULL, updated_at DATETIME NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_D89C72EDC33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_category (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) DEFAULT NULL, date DATE DEFAULT NULL, lesson_start INT NOT NULL, lesson_end INT NOT NULL, description VARCHAR(255) DEFAULT NULL, rooms JSON NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_38BBA6C69F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam_tuitions (exam_id INT UNSIGNED NOT NULL, tuition_id INT UNSIGNED NOT NULL, INDEX IDX_A472BA1A578D5E91 (exam_id), INDEX IDX_A472BA1A7FFA6BA (tuition_id), PRIMARY KEY(exam_id, tuition_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam_students (exam_id INT UNSIGNED NOT NULL, student_id INT UNSIGNED NOT NULL, INDEX IDX_E70DC281578D5E91 (exam_id), INDEX IDX_E70DC281CB944F1A (student_id), PRIMARY KEY(exam_id, student_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam_supervision (id INT UNSIGNED AUTO_INCREMENT NOT NULL, exam_id INT UNSIGNED DEFAULT NULL, teacher_id INT UNSIGNED DEFAULT NULL, lesson INT NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_2BD1F5C1578D5E91 (exam_id), INDEX IDX_2BD1F5C141807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_lesson (id INT UNSIGNED AUTO_INCREMENT NOT NULL, period_id INT UNSIGNED DEFAULT NULL, week_id INT UNSIGNED DEFAULT NULL, tuition_id INT UNSIGNED DEFAULT NULL, room_id INT UNSIGNED DEFAULT NULL, external_id VARCHAR(255) NOT NULL, day INT NOT NULL, lesson INT NOT NULL, is_double_lesson TINYINT(1) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', `type` VARCHAR(255) NOT NULL, subject VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_2628C7279F75D7B0 (external_id), INDEX IDX_2628C727EC8B7ADE (period_id), INDEX IDX_2628C727C86F3B2F (week_id), INDEX IDX_2628C7277FFA6BA (tuition_id), INDEX IDX_2628C72754177093 (room_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_lesson_teachers (timetable_lesson_id INT UNSIGNED NOT NULL, teacher_id INT UNSIGNED NOT NULL, INDEX IDX_78936A02EA4D7C00 (timetable_lesson_id), INDEX IDX_78936A0241807E1D (teacher_id), PRIMARY KEY(timetable_lesson_id, teacher_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grade (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_595AAE349F75D7B0 (external_id), UNIQUE INDEX UNIQ_595AAE345E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grade_teacher (teacher_id INT UNSIGNED NOT NULL, grade_id INT UNSIGNED NOT NULL, type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:grade_teacher_type)\', INDEX IDX_4ABB343741807E1D (teacher_id), INDEX IDX_4ABB3437FE19A1A8 (grade_id), PRIMARY KEY(teacher_id, grade_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ics_access_token (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, token VARCHAR(128) NOT NULL, type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:ics_access_token_type)\', name VARCHAR(255) NOT NULL, registered DATETIME NOT NULL, last_active DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_2E41884B5F37A13B (token), INDEX IDX_2E41884BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE import_date_time (id INT UNSIGNED AUTO_INCREMENT NOT NULL, entity_class VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_128BA50D41BF2C66 (entity_class), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infotext (id INT UNSIGNED AUTO_INCREMENT NOT NULL, date DATE NOT NULL, content LONGTEXT NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message (id INT UNSIGNED AUTO_INCREMENT NOT NULL, created_by_id INT UNSIGNED DEFAULT NULL, updated_by_id INT UNSIGNED DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, start_date DATETIME NOT NULL, expire_date DATETIME NOT NULL, scope VARCHAR(255) NOT NULL COMMENT \'(DC2Type:message_scope)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_downloads_enabled TINYINT(1) NOT NULL, is_uploads_enabled TINYINT(1) NOT NULL, upload_description LONGTEXT DEFAULT NULL, is_email_notification_sent TINYINT(1) NOT NULL, is_push_notification_sent TINYINT(1) NOT NULL, must_confirm TINYINT(1) NOT NULL, priority VARCHAR(255) NOT NULL COMMENT \'(DC2Type:message_priority)\', uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_B6BD307FB03A8386 (created_by_id), INDEX IDX_B6BD307F896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_studygroups (message_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_4550DBF5537A1329 (message_id), INDEX IDX_4550DBF55DDDCCCE (study_group_id), PRIMARY KEY(message_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_visibilities (message_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_A7AD7AA9537A1329 (message_id), INDEX IDX_A7AD7AA95E66E314 (user_type_entity_id), PRIMARY KEY(message_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_download_usertypes (message_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_38D89C91537A1329 (message_id), INDEX IDX_38D89C915E66E314 (user_type_entity_id), PRIMARY KEY(message_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_download_studygroups (message_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_638F7119537A1329 (message_id), INDEX IDX_638F71195DDDCCCE (study_group_id), PRIMARY KEY(message_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_upload_usertypes (message_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_17AD59BA537A1329 (message_id), INDEX IDX_17AD59BA5E66E314 (user_type_entity_id), PRIMARY KEY(message_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_upload_studygroups (message_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_FEF1953A537A1329 (message_id), INDEX IDX_FEF1953A5DDDCCCE (study_group_id), PRIMARY KEY(message_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_confirmation_usertypes (message_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_7F22A1537A1329 (message_id), INDEX IDX_7F22A15E66E314 (user_type_entity_id), PRIMARY KEY(message_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_confirmation_studygroups (message_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_9010E1C6537A1329 (message_id), INDEX IDX_9010E1C65DDDCCCE (study_group_id), PRIMARY KEY(message_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_attachment (id INT UNSIGNED AUTO_INCREMENT NOT NULL, message_id INT UNSIGNED DEFAULT NULL, filename VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, size INT NOT NULL, updated_at DATETIME NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_B68FF524537A1329 (message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_confirmation (message_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_8C3C27DA537A1329 (message_id), INDEX IDX_8C3C27DAA76ED395 (user_id), PRIMARY KEY(message_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_file (id INT UNSIGNED AUTO_INCREMENT NOT NULL, message_id INT UNSIGNED DEFAULT NULL, label VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_250AADC9537A1329 (message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_file_upload (message_file_id INT UNSIGNED NOT NULL, user_id INT UNSIGNED NOT NULL, filename VARCHAR(255) DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, size INT DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_CFD59E593434360 (message_file_id), INDEX IDX_CFD59E59A76ED395 (user_id), PRIMARY KEY(message_file_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth_client_info (id INT UNSIGNED AUTO_INCREMENT NOT NULL, client_id VARCHAR(32) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_46345E9E19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE privacy_category (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) DEFAULT NULL, label VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_1B8576429F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE room (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) DEFAULT NULL, name VARCHAR(16) NOT NULL, `description` LONGTEXT DEFAULT NULL, capacity INT DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_729F519B9F75D7B0 (external_id), UNIQUE INDEX UNIQ_729F519B5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE room_reservation (id INT UNSIGNED AUTO_INCREMENT NOT NULL, room_id INT UNSIGNED DEFAULT NULL, teacher_id INT UNSIGNED DEFAULT NULL, date DATE NOT NULL, lesson_start INT NOT NULL, lesson_end INT NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_56FDE76A54177093 (room_id), INDEX IDX_56FDE76A41807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE room_tag (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, description LONGTEXT DEFAULT NULL, has_value TINYINT(1) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE room_roomtags (room_id INT UNSIGNED NOT NULL, tag_id INT UNSIGNED NOT NULL, value INT DEFAULT NULL, INDEX IDX_80B7F00554177093 (room_id), INDEX IDX_80B7F005BAD26311 (tag_id), PRIMARY KEY(room_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting (`key` VARCHAR(255) NOT NULL, value LONGTEXT NOT NULL COMMENT \'(DC2Type:object)\', PRIMARY KEY(`key`)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student (id INT UNSIGNED AUTO_INCREMENT NOT NULL, grade_id INT UNSIGNED DEFAULT NULL, external_id VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, gender VARCHAR(255) NOT NULL COMMENT \'(DC2Type:gender)\', email VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, is_full_aged TINYINT(1) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_B723AF339F75D7B0 (external_id), INDEX IDX_B723AF33FE19A1A8 (grade_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE student_approved_privacy_categories (student_id INT UNSIGNED NOT NULL, privacy_category_id INT UNSIGNED NOT NULL, INDEX IDX_42D136F6CB944F1A (student_id), INDEX IDX_42D136F6F1E8355A (privacy_category_id), PRIMARY KEY(student_id, privacy_category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE study_group (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:study_group_type)\', uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_32BA14259F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE study_group_grades (study_group_id INT UNSIGNED NOT NULL, grade_id INT UNSIGNED NOT NULL, INDEX IDX_C647F0BA5DDDCCCE (study_group_id), INDEX IDX_C647F0BAFE19A1A8 (grade_id), PRIMARY KEY(study_group_id, grade_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE study_group_membership (study_group_id INT UNSIGNED NOT NULL, student_id INT UNSIGNED NOT NULL, type VARCHAR(255) DEFAULT NULL, INDEX IDX_26983EF95DDDCCCE (study_group_id), INDEX IDX_26983EF9CB944F1A (student_id), PRIMARY KEY(study_group_id, student_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) DEFAULT NULL, abbreviation VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, replace_subject_abbreviation TINYINT(1) NOT NULL, is_visible_grades TINYINT(1) NOT NULL, is_visible_students TINYINT(1) NOT NULL, is_visible_teachers TINYINT(1) NOT NULL, is_visible_rooms TINYINT(1) NOT NULL, is_visible_subjects TINYINT(1) NOT NULL, is_visible_lists TINYINT(1) NOT NULL, color VARCHAR(255) DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_FBCE3E7A9F75D7B0 (external_id), UNIQUE INDEX UNIQ_FBCE3E7ABCF3411D (abbreviation), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE substitution (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) NOT NULL, date DATE NOT NULL, lesson_start INT NOT NULL, lesson_end INT NOT NULL, starts_before TINYINT(1) NOT NULL, type VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, replacement_subject VARCHAR(255) DEFAULT NULL, room VARCHAR(255) DEFAULT NULL, replacement_room VARCHAR(255) DEFAULT NULL, remark VARCHAR(255) DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_C7C90AE09F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE substitution_teachers (substitution_id INT UNSIGNED NOT NULL, teacher_id INT UNSIGNED NOT NULL, INDEX IDX_3D5933E1D7F487C9 (substitution_id), INDEX IDX_3D5933E141807E1D (teacher_id), PRIMARY KEY(substitution_id, teacher_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE substitution_replacement_teachers (substitution_id INT UNSIGNED NOT NULL, teacher_id INT UNSIGNED NOT NULL, INDEX IDX_DA62411DD7F487C9 (substitution_id), INDEX IDX_DA62411D41807E1D (teacher_id), PRIMARY KEY(substitution_id, teacher_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE substitution_studygroups (substitution_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_89A42774D7F487C9 (substitution_id), INDEX IDX_89A427745DDDCCCE (study_group_id), PRIMARY KEY(substitution_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE substitution_replacement_studygroups (substitution_id INT UNSIGNED NOT NULL, study_group_id INT UNSIGNED NOT NULL, INDEX IDX_99785F77D7F487C9 (substitution_id), INDEX IDX_99785F775DDDCCCE (study_group_id), PRIMARY KEY(substitution_id, study_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) NOT NULL, acronym VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, gender VARCHAR(255) NOT NULL COMMENT \'(DC2Type:gender)\', email VARCHAR(255) DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_B0F6A6D59F75D7B0 (external_id), UNIQUE INDEX UNIQ_B0F6A6D5512D8851 (acronym), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_subjects (teacher_id INT UNSIGNED NOT NULL, subject_id INT UNSIGNED NOT NULL, INDEX IDX_AA332A9C41807E1D (teacher_id), INDEX IDX_AA332A9C23EDC87 (subject_id), PRIMARY KEY(teacher_id, subject_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_tags (teacher_id INT UNSIGNED NOT NULL, teacher_tag_id INT UNSIGNED NOT NULL, INDEX IDX_4E00F31741807E1D (teacher_id), INDEX IDX_4E00F317AF59B1E4 (teacher_tag_id), PRIMARY KEY(teacher_id, teacher_tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_tag (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_B1A33B79F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_period (id INT UNSIGNED AUTO_INCREMENT NOT NULL, external_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, start DATETIME NOT NULL, end DATETIME NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_1BE4AD1A9F75D7B0 (external_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_period_visibilities (timetable_period_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_1954F2D6CB3E0748 (timetable_period_id), INDEX IDX_1954F2D65E66E314 (user_type_entity_id), PRIMARY KEY(timetable_period_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_supervision (id INT UNSIGNED AUTO_INCREMENT NOT NULL, period_id INT UNSIGNED DEFAULT NULL, week_id INT UNSIGNED DEFAULT NULL, teacher_id INT UNSIGNED DEFAULT NULL, external_id VARCHAR(255) NOT NULL, day INT NOT NULL, lesson INT NOT NULL, is_before TINYINT(1) NOT NULL, location VARCHAR(255) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_396D5F689F75D7B0 (external_id), INDEX IDX_396D5F68EC8B7ADE (period_id), INDEX IDX_396D5F68C86F3B2F (week_id), INDEX IDX_396D5F6841807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE timetable_week (id INT UNSIGNED AUTO_INCREMENT NOT NULL, `key` VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, week_mod INT NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_CE6683CE4E645A7E (`key`), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tuition (id INT UNSIGNED AUTO_INCREMENT NOT NULL, subject_id INT UNSIGNED DEFAULT NULL, teacher_id INT UNSIGNED DEFAULT NULL, study_group_id INT UNSIGNED DEFAULT NULL, external_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', UNIQUE INDEX UNIQ_A1B25E5B9F75D7B0 (external_id), INDEX IDX_A1B25E5B23EDC87 (subject_id), INDEX IDX_A1B25E5B41807E1D (teacher_id), INDEX IDX_A1B25E5B5DDDCCCE (study_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tuition_additional_teachers (tuition_id INT UNSIGNED NOT NULL, teacher_id INT UNSIGNED NOT NULL, INDEX IDX_CD0280547FFA6BA (tuition_id), INDEX IDX_CD02805441807E1D (teacher_id), PRIMARY KEY(tuition_id, teacher_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_type_entity (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_type VARCHAR(255) NOT NULL COMMENT \'(DC2Type:user_type)\', UNIQUE INDEX UNIQ_84E4E6C5F65F1BE0 (user_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_web_push_subscription (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, subscription_hash VARCHAR(255) NOT NULL, subscription JSON NOT NULL, INDEX IDX_260A81F9A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wiki (id INT UNSIGNED AUTO_INCREMENT NOT NULL, root_id INT UNSIGNED DEFAULT NULL, title VARCHAR(255) NOT NULL, is_online TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, content LONGTEXT NOT NULL, `left` INT NOT NULL, level INT NOT NULL, `right` INT NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:uuid)\', `parent` INT UNSIGNED DEFAULT NULL, INDEX IDX_22CDDC0679066886 (root_id), INDEX IDX_22CDDC06514BFC18 (`parent`), FULLTEXT INDEX IDX_22CDDC062B36786B (title), FULLTEXT INDEX IDX_22CDDC06FEC530A9 (content), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wiki_article_visibilities (wiki_article_id INT UNSIGNED NOT NULL, user_type_entity_id INT UNSIGNED NOT NULL, INDEX IDX_2E45B22D4E9C5254 (wiki_article_id), INDEX IDX_2E45B22D5E66E314 (user_type_entity_id), PRIMARY KEY(wiki_article_id, user_type_entity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE id_entity (entity_id VARCHAR(255) NOT NULL, id VARCHAR(255) NOT NULL, expiry DATETIME NOT NULL, PRIMARY KEY(entity_id, id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log (id INT AUTO_INCREMENT NOT NULL, channel VARCHAR(255) NOT NULL, level INT NOT NULL, message LONGTEXT NOT NULL, time DATETIME NOT NULL, details LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cron_job (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, command VARCHAR(255) NOT NULL, arguments VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, running_instances INT UNSIGNED DEFAULT 0 NOT NULL, max_instances INT UNSIGNED DEFAULT 1 NOT NULL, number INT UNSIGNED DEFAULT 1 NOT NULL, period VARCHAR(255) NOT NULL, last_use DATETIME DEFAULT NULL, next_run DATETIME NOT NULL, enable TINYINT(1) DEFAULT \'1\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cron_job_result (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, cron_job_id BIGINT UNSIGNED NOT NULL, run_at DATETIME NOT NULL, run_time DOUBLE PRECISION NOT NULL, status_code INT NOT NULL, output LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_2CD346EE79099ED8 (cron_job_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_access_token (identifier CHAR(80) NOT NULL, client VARCHAR(32) NOT NULL, expiry DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', user_identifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_scope)\', revoked TINYINT(1) NOT NULL, INDEX IDX_454D9673C7440455 (client), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_authorization_code (identifier CHAR(80) NOT NULL, client VARCHAR(32) NOT NULL, expiry DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', user_identifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_scope)\', revoked TINYINT(1) NOT NULL, INDEX IDX_509FEF5FC7440455 (client), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_client (identifier VARCHAR(32) NOT NULL, secret VARCHAR(128) DEFAULT NULL, redirect_uris TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_redirect_uri)\', grants TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_grant)\', scopes TEXT DEFAULT NULL COMMENT \'(DC2Type:oauth2_scope)\', active TINYINT(1) NOT NULL, allow_plain_text_pkce TINYINT(1) DEFAULT \'0\' NOT NULL, PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE oauth2_refresh_token (identifier CHAR(80) NOT NULL, access_token CHAR(80) DEFAULT NULL, expiry DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', revoked TINYINT(1) NOT NULL, INDEX IDX_4DD90732B6A2DD68 (access_token), PRIMARY KEY(identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_students ADD CONSTRAINT FK_44E469B2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_students ADD CONSTRAINT FK_44E469B2CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_dismissed_messages ADD CONSTRAINT FK_E1D43738A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_dismissed_messages ADD CONSTRAINT FK_E1D43738537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C95DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C954177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84412469DE2 FOREIGN KEY (category_id) REFERENCES appointment_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment_studygroups ADD CONSTRAINT FK_5EE7E790E5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment_studygroups ADD CONSTRAINT FK_5EE7E7905DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment_organizers ADD CONSTRAINT FK_ABD20936E5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment_organizers ADD CONSTRAINT FK_ABD2093641807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment_visibilities ADD CONSTRAINT FK_9A6E5842E5B533F9 FOREIGN KEY (appointment_id) REFERENCES appointment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appointment_visibilities ADD CONSTRAINT FK_9A6E58425E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7612469DE2 FOREIGN KEY (category_id) REFERENCES document_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_studygroups ADD CONSTRAINT FK_A786B266C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_studygroups ADD CONSTRAINT FK_A786B2665DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_visibilities ADD CONSTRAINT FK_CE496E3EC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_visibilities ADD CONSTRAINT FK_CE496E3E5E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_authors ADD CONSTRAINT FK_2A638C8DC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_authors ADD CONSTRAINT FK_2A638C8DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_attachment ADD CONSTRAINT FK_D89C72EDC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_tuitions ADD CONSTRAINT FK_A472BA1A578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_tuitions ADD CONSTRAINT FK_A472BA1A7FFA6BA FOREIGN KEY (tuition_id) REFERENCES tuition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_students ADD CONSTRAINT FK_E70DC281578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_students ADD CONSTRAINT FK_E70DC281CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_supervision ADD CONSTRAINT FK_2BD1F5C1578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exam_supervision ADD CONSTRAINT FK_2BD1F5C141807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_lesson ADD CONSTRAINT FK_2628C727EC8B7ADE FOREIGN KEY (period_id) REFERENCES timetable_period (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_lesson ADD CONSTRAINT FK_2628C727C86F3B2F FOREIGN KEY (week_id) REFERENCES timetable_week (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_lesson ADD CONSTRAINT FK_2628C7277FFA6BA FOREIGN KEY (tuition_id) REFERENCES tuition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_lesson ADD CONSTRAINT FK_2628C72754177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE timetable_lesson_teachers ADD CONSTRAINT FK_78936A02EA4D7C00 FOREIGN KEY (timetable_lesson_id) REFERENCES timetable_lesson (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_lesson_teachers ADD CONSTRAINT FK_78936A0241807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grade_teacher ADD CONSTRAINT FK_4ABB343741807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE grade_teacher ADD CONSTRAINT FK_4ABB3437FE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ics_access_token ADD CONSTRAINT FK_2E41884BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message_studygroups ADD CONSTRAINT FK_4550DBF5537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_studygroups ADD CONSTRAINT FK_4550DBF55DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_visibilities ADD CONSTRAINT FK_A7AD7AA9537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_visibilities ADD CONSTRAINT FK_A7AD7AA95E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_download_usertypes ADD CONSTRAINT FK_38D89C91537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_download_usertypes ADD CONSTRAINT FK_38D89C915E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_download_studygroups ADD CONSTRAINT FK_638F7119537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_download_studygroups ADD CONSTRAINT FK_638F71195DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_upload_usertypes ADD CONSTRAINT FK_17AD59BA537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_upload_usertypes ADD CONSTRAINT FK_17AD59BA5E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_upload_studygroups ADD CONSTRAINT FK_FEF1953A537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_upload_studygroups ADD CONSTRAINT FK_FEF1953A5DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_confirmation_usertypes ADD CONSTRAINT FK_7F22A1537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_confirmation_usertypes ADD CONSTRAINT FK_7F22A15E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_confirmation_studygroups ADD CONSTRAINT FK_9010E1C6537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_confirmation_studygroups ADD CONSTRAINT FK_9010E1C65DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_attachment ADD CONSTRAINT FK_B68FF524537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_confirmation ADD CONSTRAINT FK_8C3C27DA537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_confirmation ADD CONSTRAINT FK_8C3C27DAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_file ADD CONSTRAINT FK_250AADC9537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_file_upload ADD CONSTRAINT FK_CFD59E593434360 FOREIGN KEY (message_file_id) REFERENCES message_file (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_file_upload ADD CONSTRAINT FK_CFD59E59A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oauth_client_info ADD CONSTRAINT FK_46345E9E19EB6921 FOREIGN KEY (client_id) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_reservation ADD CONSTRAINT FK_56FDE76A54177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_reservation ADD CONSTRAINT FK_56FDE76A41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_roomtags ADD CONSTRAINT FK_80B7F00554177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_roomtags ADD CONSTRAINT FK_80B7F005BAD26311 FOREIGN KEY (tag_id) REFERENCES room_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33FE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE student_approved_privacy_categories ADD CONSTRAINT FK_42D136F6CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE student_approved_privacy_categories ADD CONSTRAINT FK_42D136F6F1E8355A FOREIGN KEY (privacy_category_id) REFERENCES privacy_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_group_grades ADD CONSTRAINT FK_C647F0BA5DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_group_grades ADD CONSTRAINT FK_C647F0BAFE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_group_membership ADD CONSTRAINT FK_26983EF95DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE study_group_membership ADD CONSTRAINT FK_26983EF9CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_teachers ADD CONSTRAINT FK_3D5933E1D7F487C9 FOREIGN KEY (substitution_id) REFERENCES substitution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_teachers ADD CONSTRAINT FK_3D5933E141807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_replacement_teachers ADD CONSTRAINT FK_DA62411DD7F487C9 FOREIGN KEY (substitution_id) REFERENCES substitution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_replacement_teachers ADD CONSTRAINT FK_DA62411D41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_studygroups ADD CONSTRAINT FK_89A42774D7F487C9 FOREIGN KEY (substitution_id) REFERENCES substitution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_studygroups ADD CONSTRAINT FK_89A427745DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_replacement_studygroups ADD CONSTRAINT FK_99785F77D7F487C9 FOREIGN KEY (substitution_id) REFERENCES substitution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE substitution_replacement_studygroups ADD CONSTRAINT FK_99785F775DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_subjects ADD CONSTRAINT FK_AA332A9C41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_subjects ADD CONSTRAINT FK_AA332A9C23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_tags ADD CONSTRAINT FK_4E00F31741807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_tags ADD CONSTRAINT FK_4E00F317AF59B1E4 FOREIGN KEY (teacher_tag_id) REFERENCES teacher_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_period_visibilities ADD CONSTRAINT FK_1954F2D6CB3E0748 FOREIGN KEY (timetable_period_id) REFERENCES timetable_period (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_period_visibilities ADD CONSTRAINT FK_1954F2D65E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_supervision ADD CONSTRAINT FK_396D5F68EC8B7ADE FOREIGN KEY (period_id) REFERENCES timetable_period (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_supervision ADD CONSTRAINT FK_396D5F68C86F3B2F FOREIGN KEY (week_id) REFERENCES timetable_week (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timetable_supervision ADD CONSTRAINT FK_396D5F6841807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tuition ADD CONSTRAINT FK_A1B25E5B23EDC87 FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tuition ADD CONSTRAINT FK_A1B25E5B41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tuition ADD CONSTRAINT FK_A1B25E5B5DDDCCCE FOREIGN KEY (study_group_id) REFERENCES study_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tuition_additional_teachers ADD CONSTRAINT FK_CD0280547FFA6BA FOREIGN KEY (tuition_id) REFERENCES tuition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tuition_additional_teachers ADD CONSTRAINT FK_CD02805441807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_web_push_subscription ADD CONSTRAINT FK_260A81F9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE wiki ADD CONSTRAINT FK_22CDDC0679066886 FOREIGN KEY (root_id) REFERENCES wiki (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wiki ADD CONSTRAINT FK_22CDDC06514BFC18 FOREIGN KEY (`parent`) REFERENCES wiki (`id`) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wiki_article_visibilities ADD CONSTRAINT FK_2E45B22D4E9C5254 FOREIGN KEY (wiki_article_id) REFERENCES wiki (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wiki_article_visibilities ADD CONSTRAINT FK_2E45B22D5E66E314 FOREIGN KEY (user_type_entity_id) REFERENCES user_type_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cron_job_result ADD CONSTRAINT FK_2CD346EE79099ED8 FOREIGN KEY (cron_job_id) REFERENCES cron_job (id)');
        $this->addSql('ALTER TABLE oauth2_access_token ADD CONSTRAINT FK_454D9673C7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oauth2_authorization_code ADD CONSTRAINT FK_509FEF5FC7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier)');
        $this->addSql('ALTER TABLE oauth2_refresh_token ADD CONSTRAINT FK_4DD90732B6A2DD68 FOREIGN KEY (access_token) REFERENCES oauth2_access_token (identifier) ON DELETE SET NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE user_students DROP FOREIGN KEY FK_44E469B2A76ED395');
        $this->addSql('ALTER TABLE user_dismissed_messages DROP FOREIGN KEY FK_E1D43738A76ED395');
        $this->addSql('ALTER TABLE document_authors DROP FOREIGN KEY FK_2A638C8DA76ED395');
        $this->addSql('ALTER TABLE ics_access_token DROP FOREIGN KEY FK_2E41884BA76ED395');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FB03A8386');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F896DBBDE');
        $this->addSql('ALTER TABLE message_confirmation DROP FOREIGN KEY FK_8C3C27DAA76ED395');
        $this->addSql('ALTER TABLE message_file_upload DROP FOREIGN KEY FK_CFD59E59A76ED395');
        $this->addSql('ALTER TABLE user_web_push_subscription DROP FOREIGN KEY FK_260A81F9A76ED395');
        $this->addSql('ALTER TABLE appointment_studygroups DROP FOREIGN KEY FK_5EE7E790E5B533F9');
        $this->addSql('ALTER TABLE appointment_organizers DROP FOREIGN KEY FK_ABD20936E5B533F9');
        $this->addSql('ALTER TABLE appointment_visibilities DROP FOREIGN KEY FK_9A6E5842E5B533F9');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F84412469DE2');
        $this->addSql('ALTER TABLE document_studygroups DROP FOREIGN KEY FK_A786B266C33F7837');
        $this->addSql('ALTER TABLE document_visibilities DROP FOREIGN KEY FK_CE496E3EC33F7837');
        $this->addSql('ALTER TABLE document_authors DROP FOREIGN KEY FK_2A638C8DC33F7837');
        $this->addSql('ALTER TABLE document_attachment DROP FOREIGN KEY FK_D89C72EDC33F7837');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A7612469DE2');
        $this->addSql('ALTER TABLE exam_tuitions DROP FOREIGN KEY FK_A472BA1A578D5E91');
        $this->addSql('ALTER TABLE exam_students DROP FOREIGN KEY FK_E70DC281578D5E91');
        $this->addSql('ALTER TABLE exam_supervision DROP FOREIGN KEY FK_2BD1F5C1578D5E91');
        $this->addSql('ALTER TABLE timetable_lesson_teachers DROP FOREIGN KEY FK_78936A02EA4D7C00');
        $this->addSql('ALTER TABLE grade_teacher DROP FOREIGN KEY FK_4ABB3437FE19A1A8');
        $this->addSql('ALTER TABLE student DROP FOREIGN KEY FK_B723AF33FE19A1A8');
        $this->addSql('ALTER TABLE study_group_grades DROP FOREIGN KEY FK_C647F0BAFE19A1A8');
        $this->addSql('ALTER TABLE user_dismissed_messages DROP FOREIGN KEY FK_E1D43738537A1329');
        $this->addSql('ALTER TABLE message_studygroups DROP FOREIGN KEY FK_4550DBF5537A1329');
        $this->addSql('ALTER TABLE message_visibilities DROP FOREIGN KEY FK_A7AD7AA9537A1329');
        $this->addSql('ALTER TABLE message_download_usertypes DROP FOREIGN KEY FK_38D89C91537A1329');
        $this->addSql('ALTER TABLE message_download_studygroups DROP FOREIGN KEY FK_638F7119537A1329');
        $this->addSql('ALTER TABLE message_upload_usertypes DROP FOREIGN KEY FK_17AD59BA537A1329');
        $this->addSql('ALTER TABLE message_upload_studygroups DROP FOREIGN KEY FK_FEF1953A537A1329');
        $this->addSql('ALTER TABLE message_confirmation_usertypes DROP FOREIGN KEY FK_7F22A1537A1329');
        $this->addSql('ALTER TABLE message_confirmation_studygroups DROP FOREIGN KEY FK_9010E1C6537A1329');
        $this->addSql('ALTER TABLE message_attachment DROP FOREIGN KEY FK_B68FF524537A1329');
        $this->addSql('ALTER TABLE message_confirmation DROP FOREIGN KEY FK_8C3C27DA537A1329');
        $this->addSql('ALTER TABLE message_file DROP FOREIGN KEY FK_250AADC9537A1329');
        $this->addSql('ALTER TABLE message_file_upload DROP FOREIGN KEY FK_CFD59E593434360');
        $this->addSql('ALTER TABLE student_approved_privacy_categories DROP FOREIGN KEY FK_42D136F6F1E8355A');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C954177093');
        $this->addSql('ALTER TABLE timetable_lesson DROP FOREIGN KEY FK_2628C72754177093');
        $this->addSql('ALTER TABLE room_reservation DROP FOREIGN KEY FK_56FDE76A54177093');
        $this->addSql('ALTER TABLE room_roomtags DROP FOREIGN KEY FK_80B7F00554177093');
        $this->addSql('ALTER TABLE room_roomtags DROP FOREIGN KEY FK_80B7F005BAD26311');
        $this->addSql('ALTER TABLE user_students DROP FOREIGN KEY FK_44E469B2CB944F1A');
        $this->addSql('ALTER TABLE exam_students DROP FOREIGN KEY FK_E70DC281CB944F1A');
        $this->addSql('ALTER TABLE student_approved_privacy_categories DROP FOREIGN KEY FK_42D136F6CB944F1A');
        $this->addSql('ALTER TABLE study_group_membership DROP FOREIGN KEY FK_26983EF9CB944F1A');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C95DDDCCCE');
        $this->addSql('ALTER TABLE appointment_studygroups DROP FOREIGN KEY FK_5EE7E7905DDDCCCE');
        $this->addSql('ALTER TABLE document_studygroups DROP FOREIGN KEY FK_A786B2665DDDCCCE');
        $this->addSql('ALTER TABLE message_studygroups DROP FOREIGN KEY FK_4550DBF55DDDCCCE');
        $this->addSql('ALTER TABLE message_download_studygroups DROP FOREIGN KEY FK_638F71195DDDCCCE');
        $this->addSql('ALTER TABLE message_upload_studygroups DROP FOREIGN KEY FK_FEF1953A5DDDCCCE');
        $this->addSql('ALTER TABLE message_confirmation_studygroups DROP FOREIGN KEY FK_9010E1C65DDDCCCE');
        $this->addSql('ALTER TABLE study_group_grades DROP FOREIGN KEY FK_C647F0BA5DDDCCCE');
        $this->addSql('ALTER TABLE study_group_membership DROP FOREIGN KEY FK_26983EF95DDDCCCE');
        $this->addSql('ALTER TABLE substitution_studygroups DROP FOREIGN KEY FK_89A427745DDDCCCE');
        $this->addSql('ALTER TABLE substitution_replacement_studygroups DROP FOREIGN KEY FK_99785F775DDDCCCE');
        $this->addSql('ALTER TABLE tuition DROP FOREIGN KEY FK_A1B25E5B5DDDCCCE');
        $this->addSql('ALTER TABLE teacher_subjects DROP FOREIGN KEY FK_AA332A9C23EDC87');
        $this->addSql('ALTER TABLE tuition DROP FOREIGN KEY FK_A1B25E5B23EDC87');
        $this->addSql('ALTER TABLE substitution_teachers DROP FOREIGN KEY FK_3D5933E1D7F487C9');
        $this->addSql('ALTER TABLE substitution_replacement_teachers DROP FOREIGN KEY FK_DA62411DD7F487C9');
        $this->addSql('ALTER TABLE substitution_studygroups DROP FOREIGN KEY FK_89A42774D7F487C9');
        $this->addSql('ALTER TABLE substitution_replacement_studygroups DROP FOREIGN KEY FK_99785F77D7F487C9');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64941807E1D');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C941807E1D');
        $this->addSql('ALTER TABLE appointment_organizers DROP FOREIGN KEY FK_ABD2093641807E1D');
        $this->addSql('ALTER TABLE exam_supervision DROP FOREIGN KEY FK_2BD1F5C141807E1D');
        $this->addSql('ALTER TABLE timetable_lesson_teachers DROP FOREIGN KEY FK_78936A0241807E1D');
        $this->addSql('ALTER TABLE grade_teacher DROP FOREIGN KEY FK_4ABB343741807E1D');
        $this->addSql('ALTER TABLE room_reservation DROP FOREIGN KEY FK_56FDE76A41807E1D');
        $this->addSql('ALTER TABLE substitution_teachers DROP FOREIGN KEY FK_3D5933E141807E1D');
        $this->addSql('ALTER TABLE substitution_replacement_teachers DROP FOREIGN KEY FK_DA62411D41807E1D');
        $this->addSql('ALTER TABLE teacher_subjects DROP FOREIGN KEY FK_AA332A9C41807E1D');
        $this->addSql('ALTER TABLE teacher_tags DROP FOREIGN KEY FK_4E00F31741807E1D');
        $this->addSql('ALTER TABLE timetable_supervision DROP FOREIGN KEY FK_396D5F6841807E1D');
        $this->addSql('ALTER TABLE tuition DROP FOREIGN KEY FK_A1B25E5B41807E1D');
        $this->addSql('ALTER TABLE tuition_additional_teachers DROP FOREIGN KEY FK_CD02805441807E1D');
        $this->addSql('ALTER TABLE teacher_tags DROP FOREIGN KEY FK_4E00F317AF59B1E4');
        $this->addSql('ALTER TABLE timetable_lesson DROP FOREIGN KEY FK_2628C727EC8B7ADE');
        $this->addSql('ALTER TABLE timetable_period_visibilities DROP FOREIGN KEY FK_1954F2D6CB3E0748');
        $this->addSql('ALTER TABLE timetable_supervision DROP FOREIGN KEY FK_396D5F68EC8B7ADE');
        $this->addSql('ALTER TABLE timetable_lesson DROP FOREIGN KEY FK_2628C727C86F3B2F');
        $this->addSql('ALTER TABLE timetable_supervision DROP FOREIGN KEY FK_396D5F68C86F3B2F');
        $this->addSql('ALTER TABLE exam_tuitions DROP FOREIGN KEY FK_A472BA1A7FFA6BA');
        $this->addSql('ALTER TABLE timetable_lesson DROP FOREIGN KEY FK_2628C7277FFA6BA');
        $this->addSql('ALTER TABLE tuition_additional_teachers DROP FOREIGN KEY FK_CD0280547FFA6BA');
        $this->addSql('ALTER TABLE appointment_visibilities DROP FOREIGN KEY FK_9A6E58425E66E314');
        $this->addSql('ALTER TABLE document_visibilities DROP FOREIGN KEY FK_CE496E3E5E66E314');
        $this->addSql('ALTER TABLE message_visibilities DROP FOREIGN KEY FK_A7AD7AA95E66E314');
        $this->addSql('ALTER TABLE message_download_usertypes DROP FOREIGN KEY FK_38D89C915E66E314');
        $this->addSql('ALTER TABLE message_upload_usertypes DROP FOREIGN KEY FK_17AD59BA5E66E314');
        $this->addSql('ALTER TABLE message_confirmation_usertypes DROP FOREIGN KEY FK_7F22A15E66E314');
        $this->addSql('ALTER TABLE timetable_period_visibilities DROP FOREIGN KEY FK_1954F2D65E66E314');
        $this->addSql('ALTER TABLE wiki_article_visibilities DROP FOREIGN KEY FK_2E45B22D5E66E314');
        $this->addSql('ALTER TABLE wiki DROP FOREIGN KEY FK_22CDDC0679066886');
        $this->addSql('ALTER TABLE wiki DROP FOREIGN KEY FK_22CDDC06514BFC18');
        $this->addSql('ALTER TABLE wiki_article_visibilities DROP FOREIGN KEY FK_2E45B22D4E9C5254');
        $this->addSql('ALTER TABLE cron_job_result DROP FOREIGN KEY FK_2CD346EE79099ED8');
        $this->addSql('ALTER TABLE oauth2_refresh_token DROP FOREIGN KEY FK_4DD90732B6A2DD68');
        $this->addSql('ALTER TABLE oauth_client_info DROP FOREIGN KEY FK_46345E9E19EB6921');
        $this->addSql('ALTER TABLE oauth2_access_token DROP FOREIGN KEY FK_454D9673C7440455');
        $this->addSql('ALTER TABLE oauth2_authorization_code DROP FOREIGN KEY FK_509FEF5FC7440455');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_students');
        $this->addSql('DROP TABLE user_dismissed_messages');
        $this->addSql('DROP TABLE absence');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE appointment_studygroups');
        $this->addSql('DROP TABLE appointment_organizers');
        $this->addSql('DROP TABLE appointment_visibilities');
        $this->addSql('DROP TABLE appointment_category');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_studygroups');
        $this->addSql('DROP TABLE document_visibilities');
        $this->addSql('DROP TABLE document_authors');
        $this->addSql('DROP TABLE document_attachment');
        $this->addSql('DROP TABLE document_category');
        $this->addSql('DROP TABLE exam');
        $this->addSql('DROP TABLE exam_tuitions');
        $this->addSql('DROP TABLE exam_students');
        $this->addSql('DROP TABLE exam_supervision');
        $this->addSql('DROP TABLE timetable_lesson');
        $this->addSql('DROP TABLE timetable_lesson_teachers');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE grade_teacher');
        $this->addSql('DROP TABLE ics_access_token');
        $this->addSql('DROP TABLE import_date_time');
        $this->addSql('DROP TABLE infotext');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE message_studygroups');
        $this->addSql('DROP TABLE message_visibilities');
        $this->addSql('DROP TABLE message_download_usertypes');
        $this->addSql('DROP TABLE message_download_studygroups');
        $this->addSql('DROP TABLE message_upload_usertypes');
        $this->addSql('DROP TABLE message_upload_studygroups');
        $this->addSql('DROP TABLE message_confirmation_usertypes');
        $this->addSql('DROP TABLE message_confirmation_studygroups');
        $this->addSql('DROP TABLE message_attachment');
        $this->addSql('DROP TABLE message_confirmation');
        $this->addSql('DROP TABLE message_file');
        $this->addSql('DROP TABLE message_file_upload');
        $this->addSql('DROP TABLE oauth_client_info');
        $this->addSql('DROP TABLE privacy_category');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE room_reservation');
        $this->addSql('DROP TABLE room_tag');
        $this->addSql('DROP TABLE room_roomtags');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_approved_privacy_categories');
        $this->addSql('DROP TABLE study_group');
        $this->addSql('DROP TABLE study_group_grades');
        $this->addSql('DROP TABLE study_group_membership');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE substitution');
        $this->addSql('DROP TABLE substitution_teachers');
        $this->addSql('DROP TABLE substitution_replacement_teachers');
        $this->addSql('DROP TABLE substitution_studygroups');
        $this->addSql('DROP TABLE substitution_replacement_studygroups');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE teacher_subjects');
        $this->addSql('DROP TABLE teacher_tags');
        $this->addSql('DROP TABLE teacher_tag');
        $this->addSql('DROP TABLE timetable_period');
        $this->addSql('DROP TABLE timetable_period_visibilities');
        $this->addSql('DROP TABLE timetable_supervision');
        $this->addSql('DROP TABLE timetable_week');
        $this->addSql('DROP TABLE tuition');
        $this->addSql('DROP TABLE tuition_additional_teachers');
        $this->addSql('DROP TABLE user_type_entity');
        $this->addSql('DROP TABLE user_web_push_subscription');
        $this->addSql('DROP TABLE wiki');
        $this->addSql('DROP TABLE wiki_article_visibilities');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE id_entity');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE cron_job');
        $this->addSql('DROP TABLE cron_job_result');
        $this->addSql('DROP TABLE oauth2_access_token');
        $this->addSql('DROP TABLE oauth2_authorization_code');
        $this->addSql('DROP TABLE oauth2_client');
        $this->addSql('DROP TABLE oauth2_refresh_token');
    }
}
